Fix deriving with `no_std`
With `no_std`, the `std` prelude is not used, so `ToOwned` is not imported, causing:
```
error[E0599]: no method named `to_owned` found for reference `&'static str` in the current scope
...
help: items from traits can only be used if the trait is in scope
help: trait `ToOwned` which provides `to_owned` is implemented but not in scope; perhaps you want to import it
```

This commit works-around it by using `into()`, since `Into` is included in the `core` prelude (which is available even in `no_std`)